# Assignment Lab 3 - Nicolas Duboc

## Part (a) 

**Write the appropriate equation for the steady state.**

Given: 

$$\dfrac{\delta S}{\delta t} = \kappa\dfrac{\delta^2 S}{\delta x^2} - \gamma S +\alpha(x)$$

The steady state is given by:

$$0 = \kappa\dfrac{\delta^2 S}{\delta x^2} - \gamma S +\alpha(x)$$

$$\dfrac{\delta^2 S}{\delta x^2} = \dfrac{\gamma S -\alpha(x)}{\kappa} $$

## Part (b)

**Discretize the hall into N segments and write the equation for the
steady state as a matrix equation.**

Approximating $\dfrac{\delta^2 S}{\delta t^2}$ using second order centered difference: 

$$ \dfrac{S_{i+1} - 2S_{i} + S_{i-1}}{\Delta x^2}= \dfrac{\gamma S_{i}-\alpha(x)}{\kappa}$$

$$S_{i+1} - 2S_{i} + S_{i-1} = \dfrac{(\gamma S_{i} - \alpha(x) )\Delta x^2}{\kappa}$$

$$S_{i+1} - 2S_{i} + S_{i-1} -\dfrac{\gamma \Delta x^2}{\kappa} = -\dfrac{\alpha(x) \Delta x^2}{\kappa}$$

$$S_{i+1} + S_{i-1} + \dfrac{\alpha(x) \Delta x^2}{\kappa} = S_{i}(2+\dfrac{\gamma \Delta x^2}{\kappa})$$

$$S_{i+1} -S_{i}(2+\dfrac{\gamma \Delta x^2}{\kappa})+ S_{i-1}  =  -\dfrac{\alpha(x) \Delta x^2}{\kappa}$$

$$S_{i+1} -S_{i}(2+\dfrac{\gamma \Delta x^2}{\kappa})+ S_{i-1}  =  -\dfrac{\alpha(x) \Delta x^2}{\kappa}$$

Setting $z = 2+\dfrac{\gamma \Delta x^2}{\kappa}$ and $f = -\dfrac{\alpha(x) \Delta x^2}{\kappa}$

The matrix is equation is: 

$$
A 
\left(\begin{array}{cc} 
1 & 0 & 0 & 0 & 0 & 0 \\
1 & -z & 1 & 0 & 0 & 0 \\
0 & 1 & -z & 1 & 0 & 0 \\
0 & 0 & 1 & -z & 1 & 0 \\
0 & 0 & 0 & 1 & -z & 1 \\
0 & 0 & 0 & 0 & 0 & 1
\end{array}\right)
\times S 
\left(\begin{array}{cc} 
S_{0}\\ 
S_{1}\\
S_{2}\\
S_{3}\\
S_{4}\\
S_{5}\\
\end{array}\right)
=F
\left(\begin{array}{cc} 
f_{0}\\ 
f_{1}\\
f_{2}\\
f_{3}\\
f_{4}\\
f_{5}\\
\end{array}\right)
$$ 


## Part (c)

Matrix operation becomes: 

$$A \times S = F \rightarrow S = F \times A^-1$$

$x_{*}$ at $i = 3$ when $i$ starts at $0$, $z$ and $f$ become:

$z = \dfrac{\alpha_{0} \Delta x^2}{\kappa} = 2.5$  

$f = 2+\dfrac{\gamma \Delta x^2}{\kappa} \approx 2.14 $




In [1]:
import numpy as np 
def n_matrix(N,gam=True):
    A = np.zeros(shape=(N+1,N+1))
    kappa = 0.05
    if gam:
        gamma = 1/3600
    else:
        gamma = 0
    alpha_x = 0.005
    z = 2+((gamma*(N)**2)/kappa)
    disc_coeff = [1.,-z,1.] #central diff approx


    #Dirischlet
    A[0,0] = 1
    A[-1,-1] = 1
    
    for i in range(1,N):
        A[i,i-1:len(disc_coeff)+(i-1)] = disc_coeff

    S = np.zeros(N+1).reshape((N+1),1)

    F = np.zeros(N+1).reshape((N+1),1)
    F[3] = -(alpha_x*(N)**2)/kappa

    return A, S, F


In [2]:
N = 5
A,S,F  = n_matrix(N)
np.set_printoptions(linewidth=100)

In [3]:
A

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.        , -2.13888889,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        , -2.13888889,  1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        , -2.13888889,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        , -2.13888889,  1.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,  1.        ]])

In [4]:
F

array([[ 0. ],
       [ 0. ],
       [ 0. ],
       [-2.5],
       [ 0. ],
       [ 0. ]])

In [5]:
A_inv = np.linalg.inv(A)
S = A_inv*F

Solution for $S = S_{0},S_{1},S_{2}...S_{N}$ is:

In [6]:
S[3].reshape(N+1,1)

array([[-0.65172863],
       [ 0.65172863],
       [ 1.39397513],
       [ 2.32982928],
       [ 1.08927083],
       [-1.08927083]])

# Part (d)

Condition number of $A \approx 8.5$

In [7]:
np.linalg.cond(A)

8.487932986194267

# Part (e)

**If $\gamma$ is 0 what is the condition number of the matrix? (using
python) Physically why is there no single solution?**

Condition number of $A$ when $\gamma = 0$ is $\approx 11$

In [8]:
A_gamma_zero = n_matrix(N,False)
A_gamma_zero[0]

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 1., -2.,  1.,  0.,  0.,  0.],
       [ 0.,  1., -2.,  1.,  0.,  0.],
       [ 0.,  0.,  1., -2.,  1.,  0.],
       [ 0.,  0.,  0.,  1., -2.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [9]:
np.linalg.cond(A_gamma_zero[0])

10.994600319765423

Physically when $\gamma = 0$ no single solution exists because there is no measurement of how the smoke leaves the system. Therefore it's dispersion can have multiple outcomes.

## Part (f)

**If γ is 0 and α is 0, why physically is there no single solution?**

If both $\alpha = 0$ and $\gamma = 0$ no solution exists because there is no measurement of how the smoke enters and leaves the system. 